# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Flutter build app

on:
  push:
    branches:
      - 'ci_test/**'
    tags:
      - "*"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Initialize Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Get Dependencies
        run: flutter pub get
      - name: Build Windows App
        run: flutter build windows
      - name: List files
        continue-on-error: true
        run: ls
      - name: List files
        continue-on-error: true
        run: dir
      - name: Copy required dll files
        continue-on-error: true
        run: cp windows/deps/*.dll build/windows/runner/release/
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-build
          path: build/windows/runner/release

